function createfigure(cdata1, YData1, XData1, XData2, YData2, XData3, YData3, XData4, YData4, XData5, YData5, XData6, YData6, XData7, YData7)
%CREATEFIGURE(CDATA1, YDATA1, XDATA1, XDATA2, YDATA2, XDATA3, YDATA3, XDATA4, YDATA4, XDATA5, YDATA5, XDATA6, YDATA6, XDATA7, YDATA7)
%  CDATA1:  image cdata
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  XDATA4:  line xdata
%  YDATA4:  line ydata
%  XDATA5:  line xdata
%  YDATA5:  line ydata
%  XDATA6:  line xdata
%  YDATA6:  line ydata
%  XDATA7:  line xdata
%  YDATA7:  line ydata

%  Auto-generated by MATLAB on 22-Mar-2019 18:24:21

% Create figure
figure1 = figure;
colormap('gray');

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1,'Layer','top','TickDir','out',...
    'CLim',[0 255],...
    'YDir','reverse',...
    'DataAspectRatio',[1 1 1]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0.5 256.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0.5 256.5]);
box(subplot1,'on');
hold(subplot1,'on');
axis off

% Create image
image(cdata1,'Parent',subplot1,'CDataMapping','scaled');

% Create hggroup
hggroup1 = hggroup('Parent',subplot1,'Tag','impoly');

% Create patch
patch('Parent',hggroup1,'PickableParts','all','Tag','patch','YData',YData1,...
    'XData',XData1,...
    'FaceColor','none',...
    'EdgeColor','none');

% Create line
line(XData2,YData2,'Parent',hggroup1,'Tag','close line bottom',...
    'LineWidth',2.25,...
    'Color',[1 1 1]);

% Create line
line(XData2,YData2,'Parent',hggroup1,'Tag','close line top',...
    'LineWidth',0.75,...
    'Color',[0.282352941176471 0.282352941176471 0.972549019607843]);

% Create line
line(XData3,YData3,'Parent',hggroup1,'Tag','bottom line','LineWidth',2.25,...
    'Color',[1 1 1]);

% Create line
line(XData3,YData3,'Parent',hggroup1,'Tag','top line','LineWidth',0.75,...
    'Color',[0.282352941176471 0.282352941176471 0.972549019607843]);

% Create line
line(XData4,YData4,'Parent',hggroup1,'Tag','bottom line','LineWidth',2.25,...
    'Color',[1 1 1]);

% Create line
line(XData4,YData4,'Parent',hggroup1,'Tag','top line','LineWidth',0.75,...
    'Color',[0.282352941176471 0.282352941176471 0.972549019607843]);

% Create hggroup
hggroup2 = hggroup('Parent',hggroup1,'Tag','impoly vertex');

% Create line
line(XData5,YData5,'Parent',hggroup2,'HitTest','off','Tag','circle',...
    'MarkerFaceColor',[0.282352941176471 0.282352941176471 0.972549019607843],...
    'MarkerEdgeColor',[0.282352941176471 0.282352941176471 0.972549019607843],...
    'MarkerSize',4.5,...
    'Marker','o');

% Create line
line(XData5,YData5,'Parent',hggroup2,'HitTest','off','Tag','plus',...
    'MarkerSize',9,...
    'Marker','+',...
    'Color',[0.282352941176471 0.282352941176471 0.972549019607843]);

% Create hggroup
hggroup3 = hggroup('Parent',hggroup1,'Tag','impoly vertex');

% Create line
line(XData6,YData6,'Parent',hggroup3,'HitTest','off','Tag','circle',...
    'MarkerFaceColor',[0.282352941176471 0.282352941176471 0.972549019607843],...
    'MarkerEdgeColor',[0.282352941176471 0.282352941176471 0.972549019607843],...
    'MarkerSize',4.5,...
    'Marker','o');

% Create line
line(XData6,YData6,'Parent',hggroup3,'HitTest','off','Tag','plus',...
    'MarkerSize',9,...
    'Marker','+',...
    'Color',[0.282352941176471 0.282352941176471 0.972549019607843]);

% Create hggroup
hggroup4 = hggroup('Parent',hggroup1,'Tag','impoly vertex');

% Create line
line(XData7,YData7,'Parent',hggroup4,'HitTest','off','Tag','circle',...
    'MarkerFaceColor',[0.282352941176471 0.282352941176471 0.972549019607843],...
    'MarkerEdgeColor',[0.282352941176471 0.282352941176471 0.972549019607843],...
    'MarkerSize',4.5,...
    'Marker','o');

% Create line
line(XData7,YData7,'Parent',hggroup4,'HitTest','off','Tag','plus',...
    'MarkerSize',9,...
    'Marker','+',...
    'Color',[0.282352941176471 0.282352941176471 0.972549019607843]);

