clc;
clear all;
close all;
a=imread('cameraman.tif','tif');
b=imresize(a,2);
figure(1);
subplot(211);
imshow(b);
title('resized image');
c=imnoise(b,'salt & pepper',0.25);
subplot(212);
imshow(c);
title('with salt and pepper noise');
f1=medfilt2(c,[3 3]);
f2=medfilt2(c,[5 5]);
f3=medfilt2(c,[7 7]);
figure(2);
subplot(131);
imshow(f1);
title('[3 3]');
subplot(132);
imshow(f2);
title('[5 5]');
subplot(133);
imshow(f3);
title('[7 7]');
